iso_code: "SXM"
aerial_image_file: "ortho_SXM.tif"
bldgs_file: "ms_SXM.geojson"
bldgs_src: "ms"
region: "north-america"
image_urls: [
    "https://oin-hotosm-temp.s3.amazonaws.com/59ba90ef23c8440011d7b194/0/53cf7018-0035-46b3-9fb1-f694ecf4c486.tif"
]  
n_samples: 50
