project: "SLUv1"
embed_model: "ResNet50_FMOW_RGB_GASSL"
group_column: "grid_id"
test_size: 0.20
model: 'LogisticRegression'
model_params:
    penalty: ['l2', 'elasticnet']
    solver: ['saga']
    C: [0.001, 0.01, 0.1, 1.0, 10]
    class_weight: [null, "balanced"]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
n_splits: 5
cv_params:
   refit: 'f1_score'
   verbose: 1
   n_jobs: -1