path_to_images: "data/{mode}/raster/{iso_code}/tiles_{iso_code}/"
path_to_file: "data/{mode}/vector/{iso_code}/tiles_{iso_code}.geojson"
path_to_embeddings: "data/{mode}/vector/{iso_code}/embeddings/"

aerial: {
    roof_material: ["concrete/cement", "healthy_metal", "irregular_metal", "tarpaulin", "incomplete"],
    roof_pitch: ["hip", "gable", "flat", "no_roof"]
}

street_view: {
    building_material : ['Plaster', 'Wood - Polished/Crude/Plank', 'Other', 'Brick/Cement/Concrete Block'],
    building_completeness : ['Complete', 'Incomplete'],
    building_security : ['Secured', 'Unsecured'],
    building_foundation : ['Strip Foundation/Footing', 'House on Columns'],
    number_of_stories : ['Three stories and above', 'Two stories', 'One story'],
    building_occupancy : ['Residential', 'Non-residential']
}

